### ISSUE TITLE
No communication when battery is 0

### ISSUE THREAD

**Issue by enry86cami** [binsentsu/home-assistant-solaredge-modbus#123]
Hi all,
When the battery is 0 I noticed that the modbus connection stops working....
This is the log:

Error reading modbus data
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/solaredge_modbus/__init__.py", line 195, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/home/homeassistant/.homeassistant/custom_components/solaredge_modbus/__init__.py", line 251, in read_modbus_data
    and self.read_modbus_data_battery1()
  File "/home/homeassistant/.homeassistant/custom_components/solaredge_modbus/__init__.py", line 773, in read_modbus_data_battery1
    return self.read_modbus_data_battery("battery1_", 0xE100)
  File "/home/homeassistant/.homeassistant/custom_components/solaredge_modbus/__init__.py", line 858, in read_modbus_data_battery
    battery_SoC = validate(decoder.decode_32bit_float(), ">", 0.1)
  File "/home/homeassistant/.homeassistant/custom_components/solaredge_modbus/__init__.py", line 130, in validate
    raise ValueError(f"Value {value} failed validation ({comparison}{against})")
ValueError: Value 0.0 failed validation (>0.1)

Error reading modbus data
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/solaredge_modbus/__init__.py", line 195, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/home/homeassistant/.homeassistant/custom_components/solaredge_modbus/__init__.py", line 246, in read_modbus_data
    self.read_modbus_data_inverter()
  File "/home/homeassistant/.homeassistant/custom_components/solaredge_modbus/__init__.py", line 570, in read_modbus_data_inverter
    inverter_data = self.read_holding_registers(unit=self._address, address=40071, count=38)
  File "/home/homeassistant/.homeassistant/custom_components/solaredge_modbus/__init__.py", line 233, in read_holding_registers
    return self._client.read_holding_registers(address, count, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/pymodbus/client/common.py", line 114, in read_holding_registers
    return self.execute(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/pymodbus/client/sync.py", line 106, in execute
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.0.30:1502)]

When battery is 0 no data, see below:
![image](https://user-images.githubusercontent.com/54316185/202407260-8231d68c-ee3e-456e-8a54-584789d3dd76.png)

What could I check?

**Comment by ryanm101** [comment]
Change and use master branch instead of the 1.6.0 and this is fixed

**Comment by enry86cami** [comment]
> Change and use master branch instead of the 1.6.0 and this is fixed

sorry, what is master branch?

**Comment by tias2001** [comment]
Open hacs, open solaredge modbus, go to redownload, change version to
master and download

**Comment by ryanm101** [comment]
as per @tias2001 comment. Then ignore HACs telling you there is a new version until it is greater than `1.6.0`

**Comment by enry86cami** [comment]
thanks for your reply.
I downloaded the master version...
Now I'm waiting for battery goes emply....

**Comment by Zumbug** [comment]
I am using master (1.4.0) and still getting an error when the battery is on 0%:

Error reading modbus data
Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 195, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 251, in read_modbus_data
    and self.read_modbus_data_battery1()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 773, in read_modbus_data_battery1
    return self.read_modbus_data_battery("battery1_", 0xE100)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 858, in read_modbus_data_battery
    battery_SoC = validate(decoder.decode_32bit_float(), ">", 0.1)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 130, in validate
    raise ValueError(f"Value {value} failed validation ({comparison}{against})")
ValueError: Value -3.4028234663852886e+38 failed validation (>0.1)

**Comment by enry86cami** [comment]
The problem Is still present with the master version...

**Comment by ryanm101** [comment]
strange my battery is empty at the moment and it works fine.

**Comment by ryanm101** [comment]
have you tried removing and re-adding the integration?

**Comment by binsentsu** [comment]
Code change wasn't pushed out as a release yet. Release now available (V1.7.0) @enry86cami Can you retest with that release?

**Comment by enry86cami** [comment]
> Code change wasn't pushed out as a release yet. Release now available (V1.7.0) @enry86cami Can you retest with that release?

updated, I let you know....

**Comment by enry86cami** [comment]
now when the batteries are 0 the communication stay up
