### ISSUE TITLE
error reading modbus data

### ISSUE THREAD

**Issue by ChristophCaina** [binsentsu/home-assistant-solaredge-modbus#127]
Hi all,

It appears, that on certain times a day my HA server is reporting the following error from the Integration:

```
Logger: custom_components.solaredge_modbus
Source: custom_components/solaredge_modbus/__init__.py:646
Integration: SolarEdge Modbus ([documentation](https://github.com/binsentsu/home-assistant-solaredge-modbus))
First occurred: 04:01:50 (1 occurrences)
Last logged: 04:01:50
Error reading modbus data

Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 195, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 246, in read_modbus_data
    self.read_modbus_data_inverter()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 646, in read_modbus_data_inverter
    self.data["acenergy"] = round(acenergy * 0.001, 3)
OverflowError: int too large to convert to float
```

the interesting part is, that it usually happens during the night, when the inverter is in sleep mode.
I am running a Modbus Proxy in between the inverter and my Homeassistant instance, because I need to access the inverter also with other applications, but I don't think that the issue will be caused by the proxy itself...

Also the last line seems to be interesting: "int too large to convert to float"

**Comment by dick902** [comment]
This is happening to me in all versions of home-assistant-solaredge-modbus plug-in!
My error reading modbus data most likely occurs at around 05:xx AM! Not every day happen, just randomly happen a few days a time. 
Look like that may be the SolarEdge inverter doing some scheduled maintenance!

**Comment by ChristophCaina** [comment]
Yes, I don't think that it is related to the last Version.
I've seen this Error in the past, too...

**Comment by ChristophCaina** [comment]
after rolling back to 1.6.0 I am still getting some errors in the logs, but they look different :)

I think, I already reported this one here at some point - and I think, at least the validation was part of the 1.7.0 version:
```
Logger: custom_components.solaredge_modbus
Source: custom_components/solaredge_modbus/__init__.py:130
Integration: SolarEdge Modbus ([documentation](https://github.com/binsentsu/home-assistant-solaredge-modbus))
First occurred: 04:16:33 (1 occurrences)
Last logged: 04:16:33
Error reading modbus data

Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 195, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 247, in read_modbus_data
    and self.read_modbus_data_meter1()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 259, in read_modbus_data_meter1
    return self.read_modbus_data_meter("m1_", 40190)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 423, in read_modbus_data_meter
    exported = validate(self.calculate_value(exported, energywsf), ">", 0)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 130, in validate
    raise ValueError(f"Value {value} failed validation ({comparison}{against})")
ValueError: Value 0 failed validation (>0)
```

So, yes - to me it is clear, if the Meter can't report a value, it is reporting 0 - which needs somehow to be validated, but should not be passed to the sensor at all:
Logger: custom_components.solaredge_modbus
Source: custom_components/solaredge_modbus/__init__.py:130
Integration: SolarEdge Modbus ([documentation](https://github.com/binsentsu/home-assistant-solaredge-modbus))
First occurred: 04:16:33 (1 occurrences)
Last logged: 04:16:33
Error reading modbus data

```
  File "/config/custom_components/solaredge_modbus/__init__.py", line 423, in read_modbus_data_meter
    exported = validate(self.calculate_value(exported, energywsf), ">", 0)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 130, in validate
    raise ValueError(f"Value {value} failed validation ({comparison}{against})")
ValueError: Value 0 failed validation (>0)
```

So my guess at the moment is the following:

With 1.6.0 the meter reports 0 - which will cause the error to be logged.
With the changes made in 1.7.0 and the validation for >= 0 the sensor might report the zero to the sensor - which could then cause the issues observed in #126

**Comment by theneiljohnson** [comment]
I'm seeing similar but with a different error

Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.solaredge_modbus
Source: custom_components/solaredge_modbus/__init__.py:130
Integration: SolarEdge Modbus ([documentation](https://github.com/binsentsu/home-assistant-solaredge-modbus))
First occurred: 27 December 2022 at 19:17:27 (24 occurrences)
Last logged: 19:17:27

Error reading modbus data
Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 195, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 251, in read_modbus_data
    and self.read_modbus_data_battery1()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 768, in read_modbus_data_battery1
    return self.read_modbus_data_battery("battery1_", 0xE100)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 855, in read_modbus_data_battery
    battery_SoC = validate(decoder.decode_32bit_float(), ">", 0.0)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 130, in validate
    raise ValueError(f"Value {value} failed validation ({comparison}{against})")
ValueError: Value 0.0 failed validation (>0.0)

**Comment by ChristophCaina** [comment]
> Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.178.133:1502)]

So the log is just saying that it failed to connect to your inverter.
Nothing like the errors above about validation errors.

-> What Firmware is running on your Inverter? (CPU Version, etc.)
-> Are you connected with WiFi or Ethernet cable?
-> Try to use Modbus Port 502 instead of 1502

**Comment by SHMaup** [comment]
ChristophCaina,

Modbus Port 502 did the trick for me.
Thanks a lot!!

**Comment by mcolella** [comment]
I am experiencing a similar problem.
I have a Solaredge HD Wave inverter and I access it, on Modbus/tcp port 502 (I also tested 1502 but is the same), 
with a SIEMENS LOGO Plc.
I read, every 1 second, two blocks of Modbus register from 40000 to 40125 and from 40126 to 40250 for a total of 500 bytes.
Every night, at 19:00 and 5:00, modbus connection is reset by inverter and, when connection is restablished (after about 40 sec.), I got 65535 or 

32768 in inverter registers from 40071 to 40106 for just one read cycle, while registers from 40190 to 40225 return 32768 and registers from 40226 to 

40249 return zero for about 40 seconds. After this also these last register assume correct values.
I contacted Solaredge assistance and after some 
remote test they propose to replace inverter communication board as they say they have never seen such a problem...
So, I am waiting they send me a new board, although I think this is just a software 
bug, not an hardware failure.
Does anybody else checked inverter registers values when experiencing errors like "int too large to convert to float" are 
reported by HA server?

**Comment by ChristophCaina** [comment]
@mcolella : the problem here in this issue is, that everyone is adding comments with "i do have the same issue" - but the all the logs are showing different errors... so these issues are pretty much different...

We really need some sort of classification based on the actual log information - and people should carefully read their logs and not just replying to a ticket they "think it might be the same / similar" topic...

It becomes really hard to support these kind of behave here :-(

But to answer your question:
No, I haven't yet tried to read the registers directly yet.

**Comment by mcolella** [comment]
ChristophCaina,
I think is would be very useful to have a modbus register dump when problems occurs.
A good way to do this is to monitor modbus register 'C_SunSpec_DID' (40069, base 0) that should be always 101, 102 or 103. 
I suggest to monitor all inverter network traffic with Wireshark and, once the problem occurs, to analyze data using powerful Wireshark filters.
When the problem I described occurs, connection is closed by inverter and when it is re-opened, first reading of this register returns zero...

**Comment by mcolella** [comment]
> @mcolella : the problem here in this issue is, that everyone is adding comments with "i do have the same issue" - but the all the logs are showing different errors... so these issues are pretty much different...
> 
> We really need some sort of classification based on the actual log information - and people should carefully read their logs and not just replying to a ticket they "think it might be the same / similar" topic...
> 
> It becomes really hard to support these kind of behave here :-(
> 
> But to answer your question: No, I haven't yet tried to read the registers directly yet.

I have some news.
Investigating this problem i've found a more detailed document (from Sunspec) were is explained that 0xFFFF and 0x8000 register values are not illegal. Please, have a look at 4.2.5 and 6.4.1 16 points of following document. Hope this can help.
SunSpec-Device-Information-Model-Specificiation-V1-1-final
https://sunspec.org/wp-content/uploads/2022/05/SunSpec-Device-Information-Model-Specificiation-V1-1-final.pdf
