### ISSUE TITLE
OverflowError: int too large to convert to float

### ISSUE THREAD

**Issue by Cereal2nd** [binsentsu/home-assistant-solaredge-modbus#15]
version: V1.2.1
Below error is only seen once, but i think it should be handled correctly

Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 157, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 197, in read_modbus_data
    self.read_modbus_data_inverter()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 709, in read_modbus_data_inverter
    self.data["acenergy"] = round(acenergy * 0.001, 3)
OverflowError: int too large to convert to float

**Comment by mmnatas** [comment]
Just saw this tonight myself.
