### ISSUE TITLE
Not working if I'm connecting to a meter

### ISSUE THREAD

**Issue by robi59italy** [binsentsu/home-assistant-solaredge-modbus#17]
I have a Solaredge SE4000H, connected by ethernet and Rasberry with home assistant, updated to last version.

If I'm installing this integration by hacs and without meter, it's working.

If I'm trying to select a meter (1 or 2 or 3) I'm getting "unknown" value.

My meter is connected by RS485 and it's the standard modbus meter.

Even I have a battery connected to the inverter, and I can't see the level but this is another history...

**Comment by robi59italy** [comment]
Update
I make a new configuration with the FV running.. I can see the value if after highlighted meter 1 but all the values are zero.

and the AC Power is showing wrong data's... in the night is showing the real home consumption... now with FV running it's showing its production :-(

**Comment by binsentsu** [comment]
Hi, I don't have meters or battery myself at home. The data is directly read from the registers according to the sunspec, don't know what the influence of the FV is. Trying for example this library manually (https://github.com/nmakel/solaredge_modbus/) to see if it shows the same results, could give you a direction.

**Comment by robi59italy** [comment]
> Hi, I don't have meters or battery myself at home. The data is directly read from the registers according to the sunspec, don't know what the influence of the FV is. Trying for example this library manually (https://github.com/nmakel/solaredge_modbus/) to see if it shows the same results, could give you a direction.

Thanks for yr support.
I checked witht the suggested python library and it's showing the same numbers I can see in HA, including a long list of zero from smartmeter and battery.

Now I contacted Solaredge to ask support and see if I have to update the firmware. Maybe this could help

**Comment by TheLordVader** [comment]
How did it go? I have modbus meter via RS485 as well.

**Comment by robi59italy** [comment]
> How did it go? I have modbus meter via RS485 as well.

Solaredge updated my inverter remotely. I'm getting same data's but not all. The reason is Solaredge is applying Sunspec specification and this spec doesn't include all informations .. :-(

**Comment by TheLordVader** [comment]
Did you try this?

- Flick the switch on SolarEdge to P and connect your mobile device to the WiFi hotspot (password on the side of the inverter, or use the QR code + mySolarEdge app)

- Open the browser and visit http://172.16.0.1 41 and click on the “Communication” menu item
Select “RS485-2”

- Choose Protocol “SunSpec (Non-SE Logger)”, also under that set Device ID to 1 (mine was set to 5). Now some Modbus TCP requests were responding.

- Change the Protocol over to “SolarEdge Master” (now a SolarEdge logger script was getting data too)

- Change back protocol to “None”

- Power cycle the inverter for good measure, and it was all still working

Let me know if that helps.

**Comment by robi59italy** [comment]
thanks I will do. My inverter is y2018 and it has the LCD panel but the procedure should be the same.

**Comment by stepir** [comment]
I have 2020 model (no display) and browsing its IP don't expose a web UI. However I was able to enable modbus with the SetApp app. It works w/o meters but most of the useful information are missing (production, consumption and batteries levels). With the meters enabled everything stay unknown:

![image](https://user-images.githubusercontent.com/36472935/113696642-8c88b480-96d2-11eb-98d2-e57a45be438a.png)


![image](https://user-images.githubusercontent.com/36472935/113696390-387dd000-96d2-11eb-8728-913023d8b950.png)

I have 3 inverters, 1 is the production and the 2 others are 5k connected to LGCHem batteries - one those 2 is the master (the one where I have enabled modbus)

**Comment by robi59italy** [comment]
> Did you try this?
> 
> * Flick the switch on SolarEdge to P and connect your mobile device to the WiFi hotspot (password on the side of the inverter, or use the QR code + mySolarEdge app)
> * Open the browser and visit http://172.16.0.141 and click on the “Communication” menu item
>   Select “RS485-2”
> * Choose Protocol “SunSpec (Non-SE Logger)”, also under that set Device ID to 1 (mine was set to 5). Now some Modbus TCP requests were responding.
> * Change the Protocol over to “SolarEdge Master” (now a SolarEdge logger script was getting data too)
> * Change back protocol to “None”
> * Power cycle the inverter for good measure, and it was all still working
> 
> Let me know if that helps.

Tried this and it didn't work. I'm interesting to see the screenshot of somebody working with modbus + battery + smartmeter by solaredge to see which kind of data's is getting

**Comment by stepir** [comment]
> > Did you try this?
> > 
> > * Flick the switch on SolarEdge to P and connect your mobile device to the WiFi hotspot (password on the side of the inverter, or use the QR code + mySolarEdge app)
> > * Open the browser and visit http://172.16.0.141 and click on the “Communication” menu item
> >   Select “RS485-2”
> > * Choose Protocol “SunSpec (Non-SE Logger)”, also under that set Device ID to 1 (mine was set to 5). Now some Modbus TCP requests were responding.
> > * Change the Protocol over to “SolarEdge Master” (now a SolarEdge logger script was getting data too)
> > * Change back protocol to “None”
> > * Power cycle the inverter for good measure, and it was all still working
> > 
> > Let me know if that helps.
> 
> Tried this and it didn't work. I'm interesting to see the screenshot of somebody working with modbus + battery + smartmeter by solaredge to see which kind of data's is getting

@robi59italy see above - I don't get data but haven't switch to SunSpec protocol as my master inverter won't answer to http requests...

**Comment by TheLordVader** [comment]
Too bad..! 
I don't have a battery (SE15k only), but reading through the thread from this hass addon [https://github.com/erikarenhill/solaredge-modbus-hass] it seemes someone got it working with Smart Meter. Don't know the difference between the versions, and I really don't know which one to try, I have HACS also.

**Comment by stepir** [comment]
so tried and I don't think I can do it - I have 3 inverters (1 for handling 1 battery and acting as master, 1 for handling a second battery and acting as slave, 1 for the production and acting as slave). They are connected in RS485 on port 2. I think that such change will break the site communications between my inverters:

![image](https://user-images.githubusercontent.com/36472935/114164247-5c881e00-992b-11eb-93f3-5e992702531e.png)

![image](https://user-images.githubusercontent.com/36472935/114164277-64e05900-992b-11eb-9ab7-ea293ab8a7a5.png)

![image](https://user-images.githubusercontent.com/36472935/114164288-6742b300-992b-11eb-993b-81feb1a35bb2.png)

**Comment by purcell-lab** [comment]
I have two inverters and one meter which appears to be working if I select MODBUS and only meter 1, if I select any other meter I get 'unknown' for all values.

Some screen shots:

![image](https://user-images.githubusercontent.com/79175134/114980040-333d3400-9ecf-11eb-9936-7429dacbf51b.png)

![image](https://user-images.githubusercontent.com/79175134/114980097-4cde7b80-9ecf-11eb-98bd-ac7aacd05ad3.png)

![image](https://user-images.githubusercontent.com/79175134/114980124-58ca3d80-9ecf-11eb-875b-8d28d2979815.png)

![image](https://user-images.githubusercontent.com/79175134/114980152-64b5ff80-9ecf-11eb-9815-01855d0c16a0.png)

![image](https://user-images.githubusercontent.com/79175134/114980198-75667580-9ecf-11eb-99c6-b68e6e4ab629.png)

**Comment by stepir** [comment]
Yes as said I have a master (with battery and meter) + 2 slave (1 for PV and 1 for another master). I see the same results.

BTW the thing I'm mostly missing is then the PV and the overall battery capacity and power of my batteries.

The latter can be achieved by querying the following registers

- name: battery
  type: default
  power:
    type: modbus
    uri: 192.168.2.15:502
    id: 1
    register:
      address: 62836
      type: holding
      decode: float32s
    scale: -1
  soc:
    type: modbus
    uri: 192.168.2.15:502
    id: 1
    register:
      address: 62852
      type: holding
      decode: float32s

This is my understanding by using https://github.com/andig/evcc and haven't still figure out the PV part.

The end story is that if this plugin won't come up with such info I don't see how we could replace the standard cloud based plugin of HA.

**Comment by robi59italy** [comment]
@stepir you are right, I'm working with a mix .. the hope is sunspec protocol will include FV info in the future.

**Comment by stepir** [comment]
check this thread at evcc as they seems to have figure out also the FV

https://github.com/andig/evcc/discussions/665

**Comment by robi59italy** [comment]
> check this thread at evcc as they seems to have figure out also the FV
> 
> [andig/evcc#665](https://github.com/andig/evcc/discussions/665)

Yes very good thanks

**Comment by TheLordVader** [comment]
Yes, that's correct. Please post how it went :-)

**Comment by TheLordVader** [comment]
Well, there seems to be some issue with some settings remaining remembered
in the add on. I would configure the inverter to talk with the new meter on
channel 2, that way it won't cause any issues on bisentsu add on.

But, I you are willing to try meter 1 again I personally would go for that
first.

**Comment by ChristophCaina** [comment]
I would suggest to add a setup guide to the Wiki - and this issue itself could be closed then... ?

**Comment by pczolee** [comment]
Hello.

I have the same problem, If I setup the meter 1 then there is no data. In the log there is some error:

Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 187, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 229, in read_modbus_data
    and self.read_modbus_data_meter1()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 241, in read_modbus_data_meter1
    return self.read_modbus_data_meter("m1_", 40190)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 405, in read_modbus_data_meter
    exported = validate(self.calculate_value(exported, energywsf), ">", 0)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 124, in validate
    raise ValueError(f"Value {value} failed validation ({comparison}{against})")
ValueError: Value 0 failed validation (>0)

Without meter 1 everything looks good. I tried to change the protocol to sunspec, but if i do it than I cannot use the meter to limit my export to grid energy... So the question is how can I manage to work the energy meter with inverter and to read data from it.

Thanks

**Comment by mpredfearn** [comment]
@pczolee the value being read from the meter is failing validation:
`
exported = validate(self.calculate_value(exported, energywsf), ">", 0)
File "/config/custom_components/solaredge_modbus/init.py", line 124, in validate
raise ValueError(f"Value {value} failed validation ({comparison}{against})")
**ValueError: Value 0 failed validation (>0)**
`
The meter value for "exported energy" is 0 - that is likely impossible as it implies that the system has never exported any power. Are you sure that your system is physically wired / configured to use meter 1?

**Comment by pczolee** [comment]
> @pczolee the value being read from the meter is failing validation:
> 
> exported = validate(self.calculate_value(exported, energywsf), ">", 0) File "/config/custom_components/solaredge_modbus/init.py", line 124, in validate raise ValueError(f"Value {value} failed validation ({comparison}{against})") **ValueError: Value 0 failed validation (>0)**
> 
> The meter value for "exported energy" is 0 - that is likely impossible as it implies that the system has never exported any power. Are you sure that your system is physically wired / configured to use meter 1?

Well, I use the meter to limit the export. So the export is set to 0W. So the answer is, it can be 0. Otherwise the wiring etc is good, because I can see the values with setapp...
Thanks

**Comment by mpredfearn** [comment]
@pczolee wow I'm amazed that even with export limit set to 0, 0Wh of energy have been exported in all time - I would have expected a small amount of leakage as the system reacts to transients, etc.

Anyway, I've made a PR to remove the validation of export being > 0. The only other validation performed of meter registers is that import is > 0. I assume that this will always be the case because surely all systems must pull from the grid at some point.

https://github.com/binsentsu/home-assistant-solaredge-modbus/pull/76

**Comment by pczolee** [comment]
> @pczolee wow I'm amazed that even with export limit set to 0, 0Wh of energy have been exported in all time - I would have expected a small amount of leakage as the system reacts to transients, etc.
> 
> Anyway, I've made a PR to remove the validation of export being > 0. The only other validation performed of meter registers is that import is > 0. I assume that this will always be the case because surely all systems must pull from the grid at some point.
> 
> #76

Thanks. I going to have a look and let you know!

**Comment by pczolee** [comment]
> @pczolee wow I'm amazed that even with export limit set to 0, 0Wh of energy have been exported in all time - I would have expected a small amount of leakage as the system reacts to transients, etc.
> 
> Anyway, I've made a PR to remove the validation of export being > 0. The only other validation performed of meter registers is that import is > 0. I assume that this will always be the case because surely all systems must pull from the grid at some point.
> 
> #76

Unfortunately, still there is something wrong:

Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 187, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 229, in read_modbus_data
    and self.read_modbus_data_meter1()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 241, in read_modbus_data_meter1
    return self.read_modbus_data_meter("m1_", 40190)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 409, in read_modbus_data_meter
    imported = validate(self.calculate_value(imported, energywsf), ">", 0)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 124, in validate
    raise ValueError(f"Value {value} failed validation ({comparison}{against})")
ValueError: Value 0 failed validation (>0)

**Comment by mpredfearn** [comment]
Hey @pczolee this is the validation of the *imported* energy failing - it is also zero. Your system has never measured any imported energy either?

**Comment by pczolee** [comment]
@mpredfearn Well, of course the imported is not zero! What else can be the problem?

**Comment by pczolee** [comment]
Well, with https://github.com/nmakel/solaredge_modbus/ I try to connect (with example.py), and it show:

Registers:
	Manufacturer: SolarEdge
	Model: SE50K-RW0P0BNY4
	Type: Three Phase Inverter
	Version: 0004.0014.0107
	Serial: XXXXXXX
	Status: Producing
	Temperature: 39.12°C
	Current: 13.06A
	Phase 1 Current: 4.31A
	Phase 2 Current: 4.40A
	Phase 3 Current: 4.34A
	Phase 1 voltage: 404.10V
	Phase 2 voltage: 405.80V
	Phase 3 voltage: 406.20V
	Phase 1-N voltage: 234.00V
	Phase 2-N voltage: 232.80V
	Phase 3-N voltage: 235.40V
	Frequency: 50.03Hz
	Power: 2919.00W
	Power (Apparent): 3033.00VA
	Power (Reactive): -826.00VAr
	Power Factor: -98.42%
	Total Energy: 38289Wh
	DC Current: 3.97A
	DC Voltage: 0.00V
	DC Power: 2963.40W

Should I see the meter as well here?

**Comment by pczolee** [comment]
I think I have to give the unit for the example.py, so the meter have number 2 address:

./example.py --unit 2 192.168.8.7 1502
Inverter(192.168.8.7:1502, connectionType.TCP: timeout=1, retries=3, unit=0x2):

Registers:
Traceback (most recent call last):
  File "./example.py", line 46, in <module>
    print(f"\tManufacturer: {values['c_manufacturer']}")
KeyError: 'c_manufacturer'

If I right than I should see the meter details here, but nothing... I have no idea why. If it helping I can make screenshot from the setapp.

**Comment by mpredfearn** [comment]
@pczolee The register addresses of the meters are different to the inverter, so just changing the unit address won't work. The inverter registers are at address 40071, meter 1 at 40190, meter 2 at 40364 and meter 3 at 40539 all on the same unit address.

I haven't used https://github.com/nmakel/solaredge_modbus/ but looks like a useful library. The example.py doesn't appear to support reading meters, but there is documentation in the Readme about how to read them from an interactive Python shell. It would definitely be worth trying to read the meter registers that way to see if it agrees with what the integration is reading.

**Comment by pczolee** [comment]
Are there any tool what I can use to test that the communication via modbus tcp with the meter is working? The https://github.com/nmakel/solaredge_modbus/ can read the meter I just don't know how should I use to do it...

**Comment by mpredfearn** [comment]
Hey @pczolee - so I had a go with the library - example.py does support reading meters / batteries but it only dumps their content to json. FYI here is what I get if I run it for my system:
`
./example.py --json 192.168.1.187 502 
{
    "c_manufacturer": "SolarEdge",
    "c_model": "SE3680",
    "c_version": "0003.2724",
    "c_serialnumber": "731C26F1",
    "c_deviceaddress": 1,
    "c_sunspec_did": 101,
    "current": 167,
    "l1_current": 167,
    "l2_current": 0,
    "l3_current": 0,
    "current_scale": -2,
    "l1_voltage": 2363,
    "l2_voltage": 0,
    "l3_voltage": 0,
    "l1n_voltage": 0,
    "l2n_voltage": 0,
    "l3n_voltage": 0,
    "voltage_scale": -1,
    "power_ac": 3649,
    "power_ac_scale": -1,
    "frequency": 50026,
    "frequency_scale": -3,
    "power_apparent": 3966,
    "power_apparent_scale": -1,
    "power_reactive": 15543,
    "power_reactive_scale": -2,
    "power_factor": 9200,
    "power_factor_scale": -2,
    "energy_total": 12245720,
    "energy_total_scale": 0,
    "current_dc": 8914,
    "current_dc_scale": -4,
    "voltage_dc": 4155,
    "voltage_dc_scale": -1,
    "power_dc": 3704,
    "power_dc_scale": -1,
    "temperature": 3840,
    "temperature_scale": -2,
    "status": 4,
    "vendor_status": 0,
    "rrcr_state": 0,
    "active_power_limit": 100,
    "cosphi": 0,
    "meters": {
        "Meter1": {
            "c_manufacturer": "WattNode",
            "c_model": "WND-3Y-400-MB",
            "c_option": "Export+Import",
            "c_version": "25",
            "c_serialnumber": "4125226",
            "c_deviceaddress": 2,
            "c_sunspec_did": 203,
            "current": 0,
            "l1_current": 0,
            "l2_current": 0,
            "l3_current": 0,
            "current_scale": -1,
            "voltage_ln": 23652,
            "l1n_voltage": 23652,
            "l2n_voltage": 0,
            "l3n_voltage": 0,
            "voltage_ll": 23446,
            "l12_voltage": 23430,
            "l23_voltage": 0,
            "l31_voltage": 23462,
            "voltage_scale": -2,
            "frequency": 5003,
            "frequency_scale": -2,
            "power": -13,
            "l1_power": -13,
            "l2_power": 0,
            "l3_power": 0,
            "power_scale": 0,
            "power_apparent": 431,
            "l1_power_apparent": 431,
            "l2_power_apparent": 0,
            "l3_power_apparent": 0,
            "power_apparent_scale": 0,
            "power_reactive": -431,
            "l1_power_reactive": -431,
            "l2_power_reactive": 0,
            "l3_power_reactive": 0,
            "power_reactive_scale": 0,
            "power_factor": 5215,
            "l1_power_factor": -4354,
            "l2_power_factor": 10000,
            "l3_power_factor": 10000,
            "power_factor_scale": -2,
            "export_energy_active": 4251692,
            "l1_export_energy_active": 4251692,
            "l2_export_energy_active": 0,
            "l3_export_energy_active": 0,
            "import_energy_active": 7820016,
            "l1_import_energy_active": 7820016,
            "l2_import_energy_active": 0,
            "l3_import_energy_active": 0,
            "energy_active_scale": 0,
            "export_energy_apparent": 0,
            "l1_export_energy_apparent": 0,
            "l2_export_energy_apparent": 0,
            "l3_export_energy_apparent": 0,
            "import_energy_apparent": 0,
            "l1_import_energy_apparent": 0,
            "l2_import_energy_apparent": 0,
            "l3_import_energy_apparent": 0,
            "energy_apparent_scale": -32768,
            "import_energy_reactive_q1": 0,
            "l1_import_energy_reactive_q1": 0,
            "l2_import_energy_reactive_q1": 0,
            "l3_import_energy_reactive_q1": 0,
            "import_energy_reactive_q2": 0,
            "l1_import_energy_reactive_q2": 0,
            "l2_import_energy_reactive_q2": 0,
            "l3_import_energy_reactive_q2": 0,
            "export_energy_reactive_q3": 0,
            "l1_export_energy_reactive_q3": 0,
            "l2_export_energy_reactive_q3": 0,
            "l3_export_energy_reactive_q3": 0,
            "export_energy_reactive_q4": 0,
            "l1_export_energy_reactive_q4": 0,
            "l2_export_energy_reactive_q4": 0,
            "l3_export_energy_reactive_q4": 0,
            "energy_reactive_scale": -32768
        }
    },
    "batteries": {
        "Battery1": {
            "c_manufacturer": "LG\u0001\u0018\u00021809209049",
            "c_model": "R11163P3SSEG11809209049",
            "c_version": "DCDC 5.4.8 BMS 1.7.0.1",
            "c_serialnumber": "1809209049",
            "c_deviceaddress": 15,
            "c_sunspec_did": 0,
            "rated_energy": 7000.0,
            "maximum_charge_continuous_power": 3500.0,
            "maximum_discharge_continuous_power": 3500.0,
            "maximum_charge_peak_power": 3500.0,
            "maximum_discharge_peak_power": 3500.0,
            "average_temperature": 21.100000381469727,
            "maximum_temperature": 0.0,
            "instantaneous_voltage": 411.3999938964844,
            "instantaneous_current": 0.6806028485298157,
            "instantaneous_power": 280.0,
            "lifetime_export_energy_counter": 2213,
            "lifetime_import_energy_counter": 100,
            "maximum_energy": 7000.0,
            "available_energy": 6251.0,
            "soh": 94.0,
            "soe": 37.993919372558594,
            "status": 3,
            "status_internal": 3,
            "event_log": 0,
            "event_log_internal": 0
        },
        "Battery2": {
            "c_manufacturer": "\u0002",
            "c_model": "False",
            "c_version": "False",
            "c_serialnumber": "False",
            "c_deviceaddress": 14,
            "c_sunspec_did": 0,
            "rated_energy": -3.4028234663852886e+38,
            "maximum_charge_continuous_power": -3.4028234663852886e+38,
            "maximum_discharge_continuous_power": -3.4028234663852886e+38,
            "maximum_charge_peak_power": -3.4028234663852886e+38,
            "maximum_discharge_peak_power": -3.4028234663852886e+38,
            "average_temperature": -3.4028234663852886e+38,
            "maximum_temperature": 0.0,
            "instantaneous_voltage": -3.4028234663852886e+38,
            "instantaneous_current": -3.4028234663852886e+38,
            "instantaneous_power": 0.0,
            "lifetime_export_energy_counter": 0,
            "lifetime_import_energy_counter": 0,
            "maximum_energy": -3.4028234663852886e+38,
            "available_energy": -3.4028234663852886e+38,
            "soh": -3.4028234663852886e+38,
            "soe": -3.4028234663852886e+38,
            "status": 7,
            "status_internal": 0,
            "event_log": 0,
            "event_log_internal": 0
        }
    }
}
`
You can see that my meter 1 is configured as an export / import meter and it's export / import values are 4.2MWh / 7.8MWh respectively. That lines up with what the integration is reading:
![Screenshot_2022-01-12_11-00-19](https://user-images.githubusercontent.com/12936891/149128239-4855581e-2679-4bea-8ef0-3200bc5aa141.png)

**Comment by pczolee** [comment]
Thanks. So i tried it:
example.py --json 192.168.8.7 1502
{
    "c_manufacturer": "SolarEdge",
    "c_model": "SE50K-RW0P0BNY4",
    "c_version": "0004.0014.0107",
    "c_serialnumber": "XXXXXX",
    "c_deviceaddress": 1,
    "c_sunspec_did": 103,
    "current": 1469,
    "l1_current": 492,
    "l2_current": 489,
    "l3_current": 487,
    "current_scale": -2,
    "l1_voltage": 4050,
    "l2_voltage": 4065,
    "l3_voltage": 4076,
    "l1n_voltage": 2346,
    "l2n_voltage": 2330,
    "l3n_voltage": 2361,
    "voltage_scale": -1,
    "power_ac": 3329,
    "power_ac_scale": 0,
    "frequency": 5004,
    "frequency_scale": -2,
    "power_apparent": 3435,
    "power_apparent_scale": 0,
    "power_reactive": -8480,
    "power_reactive_scale": -1,
    "power_factor": -9846,
    "power_factor_scale": -2,
    "energy_total": 40045,
    "energy_total_scale": 0,
    "current_dc": 45216,
    "current_dc_scale": -4,
    "voltage_dc": 0,
    "voltage_dc_scale": -32768,
    "power_dc": 3379,
    "power_dc_scale": 0,
    "temperature": 4018,
    "temperature_scale": -2,
    "status": 4,
    "vendor_status": 0,
    "rrcr_state": 0,
    "active_power_limit": 100,
    "cosphi": 0,
    "meters": {},
    "batteries": {}
}

As you can see no meters there :( . I'm going to have some screenshot from the setapp, maybe it help to find the problem...

**Comment by mpredfearn** [comment]
@pczolee OK so that means that the Meter DID registers 0x9cfc, 0x9daa, 0x9e59 are all 0. Seems strange that the inverter would be reporting these as 0 even if it is configured to use a meter. Very odd.

**Comment by pczolee** [comment]
So my setup is:
![kép](https://user-images.githubusercontent.com/27812638/149130636-712a883d-32fe-4890-b3ab-7d1dff2f3fa7.png)
![kép](https://user-images.githubusercontent.com/27812638/149130688-459a76c8-257f-4d0d-9410-c0bfd9a43daa.png)
![kép](https://user-images.githubusercontent.com/27812638/149130743-70429705-43cf-40dd-b350-c8d322f50831.png)

The meter is working:
![kép](https://user-images.githubusercontent.com/27812638/149130821-734c2c84-7c42-465a-ac84-e2d36420b933.png)

This is the other RS485 port setting (this is empty)
![kép](https://user-images.githubusercontent.com/27812638/149130902-1d89bfde-3da0-4574-aed8-f56757487624.png)

The power control part:
![kép](https://user-images.githubusercontent.com/27812638/149130957-86bcb7c2-7cf2-4949-a85f-1e5de5a948cc.png)
![kép](https://user-images.githubusercontent.com/27812638/149130984-14c1b309-c789-4ec4-bae7-fb65bec8005d.png)
![kép](https://user-images.githubusercontent.com/27812638/149131005-75234202-690d-4742-9463-0fe9087f1385.png)

And the info page:
![kép](https://user-images.githubusercontent.com/27812638/149131131-8a74c67b-0111-470a-8e5e-1925bc09ea89.png)

I have no idea what is the problem :(

**Comment by mpredfearn** [comment]
Hey @pczolee Yeah I have no idea - everything looks correct in SetApp and yet the modbus registers are not reflecting the set up correctly. To be honest, you might have to go to Solaredge support with this one, sorry.

Note that even though your export limit is set to 0, 12.45kWh has been exported - so as I expected some has leaked due to transients etc. That means the validation we do on the meter values is OK - since the value that *should* be read from the register is not 0. 

Sorry I'm not sure I can help more.

**Comment by pepsonEL** [comment]
You are conecting by wifi or by LAN ? In new FW solaredge comunication by modbus on wifi was blocked and works only LAN.,

**Comment by pczolee** [comment]
@mpredfearn Yes, I'm going to talk with the support! Well, about the 12.45kWh, there was a few hours when exported (before I set up the limit).

@pepsonEL We are on LAN. But thanks for the info ;)

**Comment by pirpy** [comment]
Hello
I recently add meter 2 to the system  but if I add meter 1 and 2 then no data is received
it only works with meter 1.
Any sugestions

**Comment by stepir** [comment]
> Hello
> I recently add meter 2 to the system but if I add meter 1 and 2 then no data is received
> it only works with meter 1.
> Any sugestions

exactly my same experience

**Comment by lorenzing** [comment]
Hi @pczolee, have you solve the problem? I'm in the same situation. Thank you so much!

**Comment by pczolee** [comment]
> Hi @pczolee, have you solve the problem? I'm in the same situation. Thank you so much!

Hi.

No, unfortunately not. I wrote to the SE support, they promised that they will sort it out and let me know, but there was no reply...

**Comment by stepir** [comment]
it's most probably a modbus misconfiguration - you might want also to check the SolarEdge Modbus Multi Device integration which seems to be better maintained https://github.com/WillCodeForCats/solaredge-modbus-multi
