### ISSUE TITLE
Invalid state encountered - State max length is 255 characters

### ISSUE THREAD

**Issue by Safritjuh** [binsentsu/home-assistant-solaredge-modbus#185]
Hi,

I'm encountering log file entries regarding the modbus integration.
Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 223, in async_refresh_modbus_data
    update_callback()
  File "/config/custom_components/solaredge_modbus/sensor.py", line 160, in _modbus_data_updated
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 865, in _async_write_ha_state
    hass.states.async_set(entity_id, state, attr, self.force_update, self._context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1650, in async_set
    state = State(
            ^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1266, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.zonnepanelen_tcp_m1_import_varh_q3. State max length is 255 characters.

I have no issues with reporting the usaga of the integration whatsoever.
Just curious what this can be and not crapping my error log :)

**Comment by Safritjuh** [comment]
This seemed to be a misconfiguration from my side. 
A extra meter was selected which does not apply to my situation.
