### ISSUE TITLE
Connection errors

### ISSUE THREAD

**Issue by mirceadamian** [binsentsu/home-assistant-solaredge-modbus#19]
Hi,

I can see frequently in the HA logs that some of the reading attempts are failing.
`2021-04-08 06:28:54 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 157, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 197, in read_modbus_data
    self.read_modbus_data_inverter()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 632, in read_modbus_data_inverter
    inverter_data = self.read_holding_registers(unit=1, address=40071, count=38)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 182, in read_holding_registers
    return self._client.read_holding_registers(address, count, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymodbus/client/common.py", line 114, in read_holding_registers
    return self.execute(request)
  File "/usr/local/lib/python3.8/site-packages/pymodbus/client/sync.py", line 106, in execute
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.178.53:1502)]
`

Running HA 2021.3.3 in a docker container on a Synology NAS. The errors are not continuous, it recovers by itself.
I have started monitoring the inverter to make sure that it does not lose the WiFi connectivity (running ping to it every 30 sec and I confirm that there is absolutely no packet loss) though the integration is configured every 10 sec (if I remember correctly).

So either there is an issue with the inverter itself or the solaredge-modbus integration.

Any advise would be great.
Thank you

**Comment by mirceadamian** [comment]
Just a bit of follow-up on this for whomever reads this.
I found couple of things:
1. The inverter was connected to the wrong WiFi node if my mesh network hence there was sometimes packet loss which might have caused the above connection errors. They were not seen initially because I was only monitoring for only few hours when I opened the ticket.
2. I have forced the inverter to move on the correct node (which is 4m away from it) and now the signal in great shape. The amount of packet loss situations have significantly decreased though they are not completely gone.
3.  I have opened a ticket with SolarEdge about why the inverter is still losing packets even though the connection is not perfect. Also even after this change I have seen a period of 20mins at 2.30AM (!!) where there was a complete blackout (which recovered by itself). Completely unexplainable.
4. I believe it right to assume that the issues are not caused by the integration which is why I will close the ticket.
