### ISSUE TITLE
Failed to set state for fall back to unknown

### ISSUE THREAD

**Issue by DonBlock** [binsentsu/home-assistant-solaredge-modbus#238]
Hi,

I'm new to Home Assistan and have just migrated from IOBroker to this Plattform.
This awesome Integration is working mostly like a charm and my dashboard including calculations is running well.
But I am encountering an issue where Home Assistant fails to set the state for several sensors, falling back to "unknown" state.
This is "just" something in the log, but I would love to not face this issue. My instance is called se instead of solaredge.

The sensors affected are:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1198
First occurred: 12:16:29 PM (5 occurrences)
Last logged: 12:16:29 PM

Failed to set state for sensor.se_m2_import_varh_q3, fall back to unknown
Failed to set state for sensor.se_m2_import_varh_q3_c, fall back to unknown
Failed to set state for sensor.se_m2_import_varh_q4_a, fall back to unknown
Failed to set state for sensor.se_m2_import_varh_q4_b, fall back to unknown
Failed to set state for sensor.se_m2_import_varh_q4_c, fall back to unknown
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1198, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2313, in async_set
    state = State(
            ^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1786, in __init__
    validate_state(state)
  File "/usr/src/homeassistant/homeassistant/core.py", line 223, in validate_state
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state with length 2031. State max length is 255 characters.

Any suggestions on how to resolve this issue would be appreciated.

Thanky you very much in advance,

Dennis

**Comment by DonBlock** [comment]
I removed m2 and m3 and got rid of the problem.
