### ISSUE TITLE
Invalid state with length 2032. State max length is 255 characters.

### ISSUE THREAD

**Issue by buttash** [binsentsu/home-assistant-solaredge-modbus#245]
I'm seeing lots of these errors:
```
2024-07-25 19:22:39.063 ERROR (MainThread) [homeassistant.helpers.entity] Failed to set state for sensor.solaredge_m2_import_varh_q3, fall back to unknown
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1205, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2302, in async_set
    state = State(
            ^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1773, in __init__
    validate_state(state)
  File "/usr/src/homeassistant/homeassistant/core.py", line 239, in validate_state
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state with length 2032. State max length is 255 characters.
```
Anything I can do to resolve?

**Comment by buttash** [comment]
Configuration issue - reading data from a non-existent meter...
