### ISSUE TITLE
solaredge_modbus not working anymore: ValueError: Value 0 failed validation (>0)

### ISSUE THREAD

**Issue by Spacerat76** [binsentsu/home-assistant-solaredge-modbus#254]
**Since yesterday the integration does not work anymore:**
Logger: custom_components.solaredge_modbus
Quelle: custom_components/solaredge_modbus/__init__.py:244
Integration: SolarEdge Modbus ([Dokumentation](https://github.com/binsentsu/home-assistant-solaredge-modbus))
Erstmals aufgetreten: 07:03:06 (2078 Vorkommnisse)
Zuletzt protokolliert: 09:56:22
Error reading modbus data

Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 244, in _refresh_modbus_data
    update_result = self.read_modbus_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solaredge_modbus/__init__.py", line 320, in read_modbus_data
    and self.read_modbus_data_meter1()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solaredge_modbus/__init__.py", line 331, in read_modbus_data_meter1
    return self.read_modbus_data_meter("m1_", 40190)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solaredge_modbus/__init__.py", line 480, in read_modbus_data_meter
    exported = validate(self.calculate_value(exported, energywsf), ">", 0)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solaredge_modbus/__init__.py", line 160, in validate
    raise ValueError(f"Value {value} failed validation ({comparison}{against})")
ValueError: Value 0 failed validation (>0)

**I am using HA 2024.8.3 / 2024.9.0.**
Inverter is connected via Wifi and the SolarEdge App is still showing all values. So the network connection is working.

**Comment by Spacerat76** [comment]
After two days it started working again.
I guess SolarEdge did something with the inverter.
I change nothing in HA.
