### ISSUE TITLE
Solaredge firmware 4.21.xx and 4.22.xx breaks remote battery storage commands

### ISSUE THREAD

**Issue by thomaslehmann1234** [binsentsu/home-assistant-solaredge-modbus#259]
Hey folks, 

I installed firmware 4.21.xx to my Solaredge SE10K-RWS and found out, that my HA remote storage commands stopped working after that upgrade, no effects from the remote battery commands. I enabled debug mode for the integration without any entries in the logs.

A test with firmware 4.22.xx resulted in the same issue. I requested a firmware rollback from Solaredge support to 4.20.xx and remote battery storage commands are back.  
 
Solaredge startet to introduce new battery profiles in the latest releases so maybe modbus registers changed.

Any ideas?

**Comment by steppige** [comment]
Hi everyone,

I can confirm that I’m experiencing the same issue after upgrading my SolarEdge SE10K-RWS firmware to 4.21.xx and 4.22.xx. Remote battery storage commands from Home Assistant stopped working completely after the update, with no visible errors in the logs—even with debug mode enabled for the integration.

Before the firmware update, everything worked flawlessly. It seems that the Modbus registers or protocols for remote battery control might have changed with the newer firmware versions.

Has anyone identified specific changes in the firmware or found a workaround to regain functionality? I’m considering contacting SolarEdge support for further clarification or requesting a rollback to version 4.20.xx as you suggested.

Thanks in advance for any insights!

**Comment by thomaslehmann1234** [comment]
I raised the issue directly in maintainer repo and got a reply. Maybe you can help finding a workaround or fix. Please join that conversation. https://github.com/biemond/solaredge.modbus/issues/109 

Thanks.

**Comment by Hoedsch** [comment]
Hi,

I have a similar effect after the SolarEdge SE5000H upgraded automatically to 4.21.23. I cannot receive any data due to data errors.

```
2024-12-06 11:04:46.448 ERROR (SyncWorker_8) [custom_components.solaredge_modbus] Error reading modbus data
Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 244, in _refresh_modbus_data
    update_result = self.read_modbus_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solaredge_modbus/__init__.py", line 324, in read_modbus_data
    and self.read_modbus_data_battery1()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solaredge_modbus/__init__.py", line 856, in read_modbus_data_battery1
    return self.read_modbus_data_battery("battery1_", 0xE100)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solaredge_modbus/__init__.py", line 958, in read_modbus_data_battery
    battery_SoC = validate(decoder.decode_32bit_float(), ">=", 0.0)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solaredge_modbus/__init__.py", line 160, in validate
    raise ValueError(f"Value {value} failed validation ({comparison}{against})")
ValueError: Value -3.4028234663852886e+38 failed validation (>=0.0)

```
At the moment there is an issue with communication between inverter and battery. With the old firmware 4,17 the battery data was displayed as null and now I run into this error. Maybe this trace snippet can be used check the verification in code.

Many thanks!

**Comment by iNaiks** [comment]
Same issue with 4.21.xx firmware. 
Asked to SolarEdge to downgrade to 4.20.xx or Lower (before I have the 4.19 or 4.17, I don't remember) 

There is anything that I can do with firmware 4.21.xx?

**Comment by iNaiks** [comment]
Downgraded to 4.20.xx from SolarEdge and all works fine

**Comment by steppige** [comment]
ok perfect thanks for your suggestion. 
How do I downgrade? Contact SolarEdge directly? By email or phone? How did you do it?

**Comment by iNaiks** [comment]
I opened a support ticket 
[Support SolarEdge](https://www.solaredge.com/es/support/system-owner)  
And in 1-5 days they do the downgrade

**Comment by peter-dolkens** [comment]
> Hi,
> 
> I have a similar effect after the SolarEdge SE5000H upgraded automatically to 4.21.23. I cannot receive any data due to data errors.
> 
> ```
> 2024-12-06 11:04:46.448 ERROR (SyncWorker_8) [custom_components.solaredge_modbus] Error reading modbus data
> Traceback (most recent call last):
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 244, in _refresh_modbus_data
>     update_result = self.read_modbus_data()
>                     ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 324, in read_modbus_data
>     and self.read_modbus_data_battery1()
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 856, in read_modbus_data_battery1
>     return self.read_modbus_data_battery("battery1_", 0xE100)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 958, in read_modbus_data_battery
>     battery_SoC = validate(decoder.decode_32bit_float(), ">=", 0.0)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 160, in validate
>     raise ValueError(f"Value {value} failed validation ({comparison}{against})")
> ValueError: Value -3.4028234663852886e+38 failed validation (>=0.0)
> ```
> 
> At the moment there is an issue with communication between inverter and battery. With the old firmware 4,17 the battery data was displayed as null and now I run into this error. Maybe this trace snippet can be used check the verification in code.
> 
> Many thanks!

Sounds like it now has a valid value but it's being mapped as a signed value instead of unsigned

**Comment by biemond** [comment]
but this is a string or not 
```
        "c_manufacturer": [0xe100, 16, 'STRING', "Manufacturer"],
```

**Comment by Mahlknecht** [comment]
After reading this thread i also thought I need a downgrade, however before Solaredge could downgrade the firmware I managed my homeassist to accept the "remote storage commands" again.  

What i guess was the reason: What changed due to the update of Solaredge FW was that the "storage control mode" entity was reset to default and Put on "Maximum self consumption" instead of in the state "Remote Control" which is needed to control the entity "remote command mode" to any of options available without falling back.
So without downgrade it worked again , I installed the latest updates of Homeassist and HACS as well as reloaded the solaredge modbus integration, to the latest release (updates available until 20.09.2025) but at the end I don't belevie it was due to the updates I made but die to the above describet resetting of the state "storage control mode" .   Hope this helps other guys who have the same problem.
