### ISSUE TITLE
After Update to HA core-2021.11.0 the sensors ar not available anymore: Log error 'failed validation'

### ISSUE THREAD

**Issue by klacol** [binsentsu/home-assistant-solaredge-modbus#68]
Hi folks,

today I have installed the HA core-2021.11.0 and now I see for the most sensors:

> Entity not available

The debug log says:

> 2021-11-04 18:55:40 ERROR (MainThread) [custom_components.solaredge_modbus] Error reading modbus data
> Traceback (most recent call last):
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 187, in async_refresh_modbus_data
>     update_result = self.read_modbus_data()
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 229, in read_modbus_data
>     and self.read_modbus_data_meter1()
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 241, in read_modbus_data_meter1
>     return self.read_modbus_data_meter("m1_", 40190)
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 405, in read_modbus_data_meter
>     exported = validate(self.calculate_value(exported, energywsf), ">", 0)
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 124, in validate
>     raise ValueError(f"Value {value} failed validation ({comparison}{against})")
> ValueError: Value 0 failed validation (>0)

Perhaps, something in HA core-2021.11.0 has changed, so that a validation now fails, that had worked before?

**Comment by klacol** [comment]
I see also this error:

> 2021-11-04 18:55:31 ERROR (MainThread) [custom_components.solaredge_modbus] Error reading modbus data
> Traceback (most recent call last):
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 187, in async_refresh_modbus_data
>     update_result = self.read_modbus_data()
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 228, in read_modbus_data
>     self.read_modbus_data_inverter()
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 552, in read_modbus_data_inverter
>     inverter_data = self.read_holding_registers(unit=1, address=40071, count=38)
>   File "/config/custom_components/solaredge_modbus/__init__.py", line 215, in read_holding_registers
>     return self._client.read_holding_registers(address, count, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/pymodbus/client/common.py", line 114, in read_holding_registers
>     return self.execute(request)
>   File "/usr/local/lib/python3.9/site-packages/pymodbus/client/sync.py", line 106, in execute
>     raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
> pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.0.68:502)]

Weird, nothing has changed. Why is there a connection problem.

**Comment by klacol** [comment]
It is something on my side.

`telnet 192.168.0.68 502`

does not give a connection
