### ISSUE TITLE
Modbus entity unkonw

### ISSUE THREAD

**Issue by meden199** [binsentsu/home-assistant-solaredge-modbus#69]
I have installed the HACS component.
Add the solarEdge to the intergrations. The devices are showing up, but all data is unknow.

Where dit I make a mistake? was it at the Modbus RS458-2 configuration?
Maybe a screenshot from a working device will help me?

**Comment by ChristophCaina** [comment]
Hi,
I've set up the RS458-2 to "SolarEdge Device"
But I will try to provide a Screenshot from my inverter Settings later today

**Comment by kazek127** [comment]
I also have issue with unknow device. I can ping my inverter. But from logs I see that component can not logon to SE inverter.
Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.solaredge_modbus
Source: custom_components/solaredge_modbus/__init__.py:215
Integration: SolarEdge Modbus (documentation)
First occurred: 17:59:12 (610 occurrences)
Last logged: 19:44:58

Error reading modbus data
Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 187, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 228, in read_modbus_data
    self.read_modbus_data_inverter()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 552, in read_modbus_data_inverter
    inverter_data = self.read_holding_registers(unit=1, address=40071, count=38)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 215, in read_holding_registers
    return self._client.read_holding_registers(address, count, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymodbus/client/common.py", line 114, in read_holding_registers
    return self.execute(request)
  File "/usr/local/lib/python3.9/site-packages/pymodbus/client/sync.py", line 106, in execute
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.30.8:1502)]

**Comment by ChristophCaina** [comment]
Hi,
sorry - due to late shift I was not able to get the data from the inverter to show my settings :-(

If you login to your inverter with SetApp, you should be able to change the settings for RS458-2.
Please post some screenshots about your settings in RS458-1 and RS458-2 this could help trying to solve your connection issues.

**Comment by kazek127** [comment]
I check the inverter again and nothing changes on it, only perform update OS of the inverter. Earlier work fine.

**Comment by ChristophCaina** [comment]
I am pretty sure, that this issue is not related with the integration itself.
Most probably it is something with your modbus settings on the inverter.

It might be, that you need to change the settings for RS458-2 temporariyl and then change them back to your original configuration.
Honestly speaking, I am not quite sure about this issue - Since you haven't provided screenshots of your settings, I cannot really compare them with my setup...

**Comment by HyperActiveJ** [comment]
If it's any value, last time I upgraded I had to do what  ChristophCaina suggested to get it to open the port = change the ra485 settings then change them back again. I went and actully changed all the settings when it didn't work the first time just changing -2.

**Comment by kazek127** [comment]
But from SE application I can see that the inverter is connecting to the power meter via RS485. I attaching screens from my inverter
![SJ1021-07E0D4A3F-14-20211110-0821-10](https://user-images.githubusercontent.com/12474375/141180543-556edecc-b590-4b72-a991-f140d33f2383.jpeg)
![SJ1021-07E0D4A3F-14-20211110-0821-41](https://user-images.githubusercontent.com/12474375/141180548-07f6ed41-a5b9-452c-b0c6-7bff43e717e3.jpeg)
![SJ1021-07E0D4A3F-14-20211110-0821-47](https://user-images.githubusercontent.com/12474375/141180550-db8b65a1-8f12-4484-8d25-77870ac0e115.jpeg)
![SJ1021-07E0D4A3F-14-20211110-0821-54](https://user-images.githubusercontent.com/12474375/141180552-816d74d8-0f14-4fd3-8060-76be2213b8dd.jpeg)
![SJ1021-07E0D4A3F-14-20211110-0822-06](https://user-images.githubusercontent.com/12474375/141180553-84a5f5be-b168-4d18-bc42-c3b98d5f9d0e.jpeg)

**Comment by ChristophCaina** [comment]
The First Connection rs458-1 seems to be OK, thus is the Connection to the Meter.

The important Connection for the Integration should be the rs458-2.
As far as I got from the Translation, the settings in rs458-2 should also be OK.

I would try to Change it to Solarlog and then Change it Back to the current setting.

**Comment by Giolovin** [comment]
I'm experiencing the same error. Has this been resolved? I'm on the latest firmware

[podrzędny](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj0x6vQnJv2AhUFP-wKHawwDygQFnoECA0QAQ&url=https%3A%2F%2Fpl.wiktionary.org%2Fwiki%2Fpodrz%25C4%2599dny&usg=AOvVaw08YGqVLusriSSlaeJPWof7)

**Comment by Giolovin** [comment]
These are my settings (in Dutch)

I'm connected with a powerline adaptor with a lan + fixed ip address on the inverter
![Printscreen](https://user-images.githubusercontent.com/41340182/155752684-bb2eee1b-db2c-4c03-99a3-5fa7b7c5e1f6.jpeg)

**Comment by kazek127** [comment]
I still have this issue. After the last update, Homeassistant SE stops working with HA. SE is pinging but I got error that HA can not connect to SE

**Comment by purcell-lab** [comment]
Are you connecting to the inverter over wifi?  ModbusTCP over wifi seems to be an issue with the new firmware.

**Comment by theneiljohnson** [comment]
I've got this issue too, can anyone help please?
![IMG_1384](https://user-images.githubusercontent.com/27012389/166744076-4aac625e-eb78-4f4c-800f-c5ae7046adde.PNG)
![IMG_1383](https://user-images.githubusercontent.com/27012389/166744078-2eb37a62-12c3-4bab-86cb-21de20f0f1a1.PNG)

**Comment by theneiljohnson** [comment]
I managed to fix my issue by disabling Modbus TCP and then re-enabling again. Very weird!

**Comment by enry86cami** [comment]
Hi all, on HA I read this:
```
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/solaredge_modbus/__init__.py", line 187, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/home/homeassistant/.homeassistant/custom_components/solaredge_modbus/__init__.py", line 228, in read_modbus_data
    self.read_modbus_data_inverter()
  File "/home/homeassistant/.homeassistant/custom_components/solaredge_modbus/__init__.py", line 552, in read_modbus_data_inverter
    inverter_data = self.read_holding_registers(unit=1, address=40071, count=38)
  File "/home/homeassistant/.homeassistant/custom_components/solaredge_modbus/__init__.py", line 215, in read_holding_registers
    return self._client.read_holding_registers(address, count, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/pymodbus/client/common.py", line 114, in read_holding_registers
    return self.execute(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/pymodbus/client/sync.py", line 106, in execute
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.0.118:1502)]
```
This is my conf:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/54316185/180603251-3f8f1ee6-d68a-42aa-b979-4811bf348154.png">

I'm connected by wifi...
