### ISSUE TITLE
entities unknown - the integration is not even querying the modbus server

### ISSUE THREAD

**Issue by stepir** [binsentsu/home-assistant-solaredge-modbus#72]
Hi

As like many other I had entities in unknown state - but I'm using evcc via modbus without issues, I decided to implement a Modbus-proxy to have multiple clients being able to query my Solaredge inverter.

Now I have the proxy in the middle - evcc still work as before, but realised that this integration is not even doing any connection to the modbus proxy (configured as server inside the integration).

Is there anything I can do to understand what's going on? HA logs are not showing anything...

**Comment by stepir** [comment]
in debug mode the integration throw this errors:

```
2021-11-16 17:24:27 ERROR (MainThread) [custom_components.solaredge_modbus] Error reading modbus data
Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 187, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 234, in read_modbus_data
    and self.read_modbus_data_battery2()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 736, in read_modbus_data_battery2
    return self.read_modbus_data_battery("battery2_", 0xE200)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 815, in read_modbus_data_battery
    battery_SoC = validate(decoder.decode_32bit_float(), ">", 0.1)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 124, in validate
    raise ValueError(f"Value {value} failed validation ({comparison}{against})")
ValueError: Value -3.4028234663852886e+38 failed validation (>0.1)
```

**Comment by stepir** [comment]
turn out it was a question of time - entities went online on their own...
