### ISSUE TITLE
Integration unable to connect via Ethernet

### ISSUE THREAD

**Issue by dgtal1** [binsentsu/home-assistant-solaredge-modbus#81]
Hi there,
Today I added this integration to my HA installation. I enabled the TCP port for ethernet in settings as described. When I check the inverter connectivity with a prot scanner it shows that port 1502 is open, but the integration is unable to connect to it.
What may be wrong?? I'm pretty sure I passed the right IP and port number to the integration setup screen. I can see the same IP and port being accessible from my mobile phone port scanner, but the integration is not able to communiacate to the inverter for some reason.

Pleaes help
```Logger: pymodbus.client.sync
Source: /usr/local/lib/python3.9/site-packages/pymodbus/client/sync.py:201
First occurred: 10:24:26 (4 occurrences)
Last logged: 10:24:57

Connection to (192.168.0.183, 1502) failed: [Errno 111] Connection refused

Logger: custom_components.solaredge_modbus
Source: custom_components/solaredge_modbus/__init__.py:215
Integration: SolarEdge Modbus (documentation)
First occurred: 10:24:36 (3 occurrences)
Last logged: 10:24:57

Error reading modbus data
Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 187, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 228, in read_modbus_data
    self.read_modbus_data_inverter()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 552, in read_modbus_data_inverter
    inverter_data = self.read_holding_registers(unit=1, address=40071, count=38)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 215, in read_holding_registers
    return self._client.read_holding_registers(address, count, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymodbus/client/common.py", line 114, in read_holding_registers
    return self.execute(request)
  File "/usr/local/lib/python3.9/site-packages/pymodbus/client/sync.py", line 106, in execute
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.0.183:1502)]
```
Please help! I find this integration to be a really good thing as it gives a lot of details abou the inverter unlike the solaredge cloud integration. I'd really like to be able to use it

**Comment by john8329** [comment]
I can confirm the default port 1502 doesn't answer, after changing it to 502 it works (tested with telnet). Probably they forgot to configure the internal firewall or want to discourage users from using the integration.
