### ISSUE TITLE
Error reading modbus meter data

### ISSUE THREAD

**Issue by blakeseufert** [binsentsu/home-assistant-solaredge-modbus#96]
Hi there, 
I'm having strange behaviour when enabling meter data for my inverter. I can add the inverter without meter data, no issue. However when i tick the collect meter data 1 2 & 3 (I have a 3 phase supply) in the HA integration everything in HASS returns unknown. I have confirmed that modbus TCP is enables and port is correct and reachable. The inverter is also reporting meter data to the cloud / app no problems.

Any help would be greatly appreciated, I have been wrestling with this for a few months now to no avail 😵‍💫.

Thanks in advance.

![image](https://user-images.githubusercontent.com/10355608/184814465-8ba994d0-7596-4b2d-857d-f36fa46f0819.png)

![PXL_20220816_063845461](https://user-images.githubusercontent.com/10355608/184814530-f6806672-ee80-4fa3-837c-97ec1f6a7fc4.jpeg)

Hass log:
```
2022-08-16 14:13:06.869 ERROR (MainThread) [custom_components.solaredge_modbus] Error reading modbus data
Traceback (most recent call last):
File "/config/custom_components/solaredge_modbus/__init__.py", line 195, in async_refresh_modbus_data
update_result = self.read_modbus_data()
File "/config/custom_components/solaredge_modbus/__init__.py", line 247, in read_modbus_data
and self.read_modbus_data_meter1()
File "/config/custom_components/solaredge_modbus/__init__.py", line 259, in read_modbus_data_meter1
return self.read_modbus_data_meter("m1_", 40190)
File "/config/custom_components/solaredge_modbus/__init__.py", line 423, in read_modbus_data_meter
exported = validate(self.calculate_value(exported, energywsf), ">", 0)
File "/config/custom_components/solaredge_modbus/__init__.py", line 130, in validate
raise ValueError(f"Value {value} failed validation ({comparison}{against})")
ValueError: Value 0.0 failed validation (>0)
2022-08-16 14:13:36.873 ERROR (MainThread) [custom_components.solaredge_modbus] Error reading modbus data
Traceback (most recent call last):
File "/config/custom_components/solaredge_modbus/__init__.py", line 195, in async_refresh_modbus_data
update_result = self.read_modbus_data()
File "/config/custom_components/solaredge_modbus/__init__.py", line 247, in read_modbus_data
and self.read_modbus_data_meter1()
File "/config/custom_components/solaredge_modbus/__init__.py", line 259, in read_modbus_data_meter1
return self.read_modbus_data_meter("m1_", 40190)
File "/config/custom_components/solaredge_modbus/__init__.py", line 423, in read_modbus_data_meter
exported = validate(self.calculate_value(exported, energywsf), ">", 0)
File "/config/custom_components/solaredge_modbus/__init__.py", line 130, in validate
```

**Comment by blakeseufert** [comment]
Figured it out.. I have one 3 phase meter, not 3 single phase meters. Set it to 1 meter and voila!

sorry for the mess around :). Now to get the energy dashboard working ....
